DROP TABLE inventory_spectrum;
CREATE TABLE inventory_spectrum (
    id SERIAL PRIMARY KEY,
    filename VARCHAR(150),
    date VARCHAR(150),
    time VARCHAR(500),
    user VARCHAR(150),
    description VARCHAR(150),
    minimum_wavelength DECIMAL(19, 3),
    equipment VARCHAR(150),
    series VARCHAR(45),
    software VARCHAR(45),
    operating_mode VARCHAR(150),
    cycles VARCHAR(150),
    slit_pmt DECIMAL(19, 3),
    response_ingaas DECIMAL(19, 3),
    response_pmt DECIMAL(19, 3),
    pmt_gain DECIMAL(19, 3),
    ingaas_gain DECIMAL(19, 3),
    monochromator_change DECIMAL(19, 3),
    lamp_change DECIMAL(19, 3),
    pmt_change DECIMAL(19, 3),
    beam_selector VARCHAR(150),
    cbm VARCHAR(150),
    cbd_status VARCHAR(150),
    attenuator_percentage_sample DECIMAL(19, 3),
    attenuator_percentage_reference DECIMAL(19, 3),
    polarizer DECIMAL(19, 3),
    units VARCHAR(150),
    measuring_mode VARCHAR(150),
    maximum_wavelength DECIMAL(19, 3),
    step DECIMAL(19, 3),
    number_of_datapoints VARCHAR(150),
    maximum_measurement DECIMAL(19, 3),
    minimum_measurement DECIMAL(19, 3),
    notes VARCHAR(250)
    #specimen VARCHAR(150),
    #FOREIGN KEY (specimen) REFERENCES inventory_specimen(code),
    #file VARCHAR(255),
    #image VARCHAR(255)
);
show columns from inventory_spectrum;

CREATE DATABASE IF NOT EXISTS inventario;
USE inventario;
CREATE TABLE IF NOT EXISTS inventory_spectrum (
    id SERIAL PRIMARY KEY,
    filename varchar(150),
    date varchar(150),
    time varchar(500),
    user varchar(150),
    description varchar(150),
    minimum_wavelength decimal(19,3),
    equipment varchar(150),
    series varchar(45),
    software varchar(250),
    operating_mode varchar(150),
    cycles varchar(150),
    slit_pmt decimal(19,3),
    response_ingaas decimal(19,3),
    response_pmt decimal(19,3),
    pmt_gain decimal(19,3),
    ingaas_gain decimal(19,3),
    monochromator_change decimal(19,3),
    lamp_change decimal(19,3),
    pmt_change decimal(19,3),
    beam_selector varchar(150),
    cbm varchar(150),
    cbd_status varchar(150),
    attenuator_percentage_sample decimal(19,3),
    attenuator_percentage_reference decimal(19,3),
    polarizer decimal(19,3),
    units varchar(150),
    measuring_mode varchar(150),
    maximum_wavelength decimal(19,3),
    step decimal(19,3),
    number_of_datapoints varchar(150),
    maximum_measurement decimal(19,3),
    minimum_measurement decimal(19,3),
    notes varchar(250),
    file varchar(255),
    specimen_id varchar(150),
    image varchar(100)
);
