# Generated by Django 5.0.1 on 2024-01-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Specimen",
            fields=[
                (
                    "code",
                    models.CharField(max_length=150, primary_key=True, serialize=False),
                ),
                ("label", models.CharField(max_length=150)),
                ("notes", models.CharField(max_length=500)),
                ("old_code", models.CharField(max_length=150)),
                ("collection_day", models.CharField(max_length=150)),
                ("collection_month", models.CharField(max_length=150)),
                ("collection_year", models.CharField(max_length=150)),
                ("death_date", models.CharField(max_length=45)),
                ("sex_code", models.CharField(max_length=45)),
                ("refrigerator", models.CharField(max_length=150)),
                ("tray", models.CharField(max_length=150)),
                ("row", models.CharField(max_length=150)),
                ("column", models.CharField(max_length=150)),
                ("location_code", models.CharField(max_length=150)),
                ("location", models.CharField(max_length=150)),
                ("genus", models.CharField(max_length=150)),
                ("species", models.CharField(max_length=150)),
                ("country", models.CharField(max_length=150)),
                ("province", models.CharField(max_length=150)),
                ("latitude", models.CharField(max_length=150)),
                ("longitude", models.CharField(max_length=150)),
                ("elevation", models.CharField(max_length=150)),
                ("light_dark", models.CharField(max_length=150)),
                ("histology_location", models.CharField(max_length=150)),
                ("histology_stage_performed", models.CharField(max_length=150)),
                ("histology_stage_next_up", models.CharField(max_length=150)),
                ("rna_location", models.CharField(max_length=150)),
                ("etoh_voucher", models.CharField(max_length=150)),
                ("elytron", models.CharField(max_length=150)),
                ("purpose", models.CharField(max_length=150)),
            ],
        ),
    ]
