# Generated by Django 5.0.1 on 2024-02-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specimen",
            name="code",
            field=models.IntegerField(
                max_length=150, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="specimen",
            name="collection_day",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="specimen",
            name="collection_month",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="specimen",
            name="collection_year",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="specimen",
            name="column",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="specimen",
            name="country",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="specimen",
            name="death_date",
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name="specimen",
            name="elevation",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="specimen",
            name="elytron",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="specimen",
            name="etoh_voucher",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="specimen",
            name="genus",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="specimen",
            name="histology_location",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="specimen",
            name="histology_stage_next_up",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="specimen",
            name="histology_stage_performed",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="specimen",
            name="label",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="specimen",
            name="latitude",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="specimen",
            name="light_dark",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="specimen",
            name="location",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="specimen",
            name="location_code",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="specimen",
            name="longitude",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="specimen",
            name="notes",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="specimen",
            name="old_code",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="specimen",
            name="province",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="specimen",
            name="purpose",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="specimen",
            name="refrigerator",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="specimen",
            name="rna_location",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="specimen",
            name="row",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="specimen",
            name="sex_code",
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name="specimen",
            name="species",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="specimen",
            name="tray",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
