# Generated by Django 5.0.1 on 2024-02-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "inventory",
            "0002_alter_specimen_code_alter_specimen_collection_day_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="specimen",
            name="code",
            field=models.CharField(max_length=150, primary_key=True, serialize=False),
        ),
    ]
