# Generated by Django 5.0.1 on 2024-02-15 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_alter_specimen_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Spectrum",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("filename", models.CharField(max_length=150, null=True)),
                ("date", models.CharField(blank=True, max_length=150, null=True)),
                ("time", models.CharField(blank=True, max_length=500, null=True)),
                ("user", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "minimum_wavelength",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=19,
                        max_length=150,
                        null=True,
                    ),
                ),
                ("equipment", models.CharField(blank=True, max_length=150, null=True)),
                ("series", models.CharField(blank=True, max_length=45, null=True)),
                ("software", models.CharField(blank=True, max_length=45, null=True)),
                (
                    "operating_mode",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("cycles", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "slit_pmt",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=19,
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "response_ingaas",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=19,
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "response_pmt",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=19,
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "pmt_gain",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=19,
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "ingaas_gain",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=19,
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "monochromator_change",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=19,
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "lamp_change",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=19,
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "pmt_change",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=19,
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "beam_selector",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("cbm", models.CharField(blank=True, max_length=150, null=True)),
                ("cbd_status", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "attenuator_percentage_sample",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=19,
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "attenuator_percentage_reference",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=19,
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "polarizer",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=19,
                        max_length=150,
                        null=True,
                    ),
                ),
                ("units", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "measuring_mode",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "maximum_wavelength",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=19,
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "step",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=19,
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "number_of_datapoints",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "maximum_measurement",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=19,
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "minimum_measurement",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=19,
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True,
                        help_text="Please add particular notes for this spectrum: ",
                        max_length=250,
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/%Y/%m/%d/")),
                (
                    "specimen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.specimen",
                    ),
                ),
            ],
        ),
    ]
