# Generated by Django 5.0.1 on 2024-02-15 14:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_spectrum"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="spectrum",
            name="specimen",
        ),
    ]
