# Generated by Django 5.0.1 on 2024-02-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0006_spectrum_specimen"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="spectrum",
            name="specimen",
        ),
        migrations.AlterField(
            model_name="spectrum",
            name="software",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
