# Generated by Django 5.0.1 on 2024-02-16 22:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0009_spectrum_image_alter_spectrum_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spectrum",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
    ]
