# Generated by Django 5.0.1 on 2024-01-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.IntegerField()),
                ("label", models.CharField(max_length=150)),
                ("notes", models.CharField(max_length=500)),
                ("old_code", models.CharField(max_length=150)),
                ("collection_day", models.CharField(max_length=150)),
                ("collection_month", models.CharField(max_length=150)),
                ("collection_year", models.CharField(max_length=150)),
                ("death_date", models.CharField(max_length=45)),
                ("sex_code", models.CharField(max_length=45)),
                ("refrigerator", models.IntegerField()),
                ("tray", models.CharField(max_length=150)),
                ("column", models.CharField(max_length=150)),
                ("location_code", models.CharField(max_length=45)),
                ("genus", models.CharField(max_length=45)),
                ("species", models.CharField(max_length=45)),
                ("country", models.CharField(max_length=45)),
                ("province", models.CharField(max_length=45)),
                ("latitude", models.CharField(max_length=45)),
                ("longitude", models.CharField(max_length=45)),
                ("elevation", models.CharField(max_length=45)),
                ("light_dark", models.CharField(max_length=45)),
                ("histology_location", models.CharField(max_length=150)),
                ("histology_stage_performed", models.CharField(max_length=150)),
                ("histology_stage_next_up", models.CharField(max_length=150)),
                ("rna_location", models.CharField(max_length=150)),
                ("etoh_voucher", models.CharField(max_length=150)),
                ("elytron", models.CharField(max_length=150)),
                ("purpose", models.CharField(max_length=150)),
            ],
        ),
    ]
