# Generated by Django 5.0.1 on 2024-01-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0002_inventario"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventario",
            name="id",
        ),
        migrations.AlterField(
            model_name="inventario",
            name="code",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
