# Generated by Django 5.0.1 on 2024-01-25 16:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0003_remove_inventario_id_alter_inventario_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventario",
            name="location",
            field=models.CharField(default="", max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="inventario",
            name="row",
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
