# Generated by Django 5.0.1 on 2024-02-07 16:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0004_inventario_location_inventario_row"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Inventario",
        ),
    ]
